# Generated by Django 2.1.dev20180313180640 on 2018-08-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounts', models.CharField(max_length=64)),
                ('accountbalances', models.CharField(max_length=64)),
                ('names', models.CharField(max_length=64)),
            ],
        ),
    ]
