# Generated by Django 2.1.dev20180313180640 on 2018-08-29 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountHolder_Type_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AcctHolderType', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Address_Type_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legalAddressType', models.CharField(blank=True, max_length=1000, null=True)),
                ('CountryCode', models.CharField(max_length=1000)),
                ('AddressFree', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddressFix_Type_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Street', models.CharField(blank=True, max_length=1000, null=True)),
                ('BuildingIdentifier', models.CharField(blank=True, max_length=1000, null=True)),
                ('SuiteIdentifier', models.CharField(blank=True, max_length=1000, null=True)),
                ('FloorIdentifier', models.CharField(blank=True, max_length=1000, null=True)),
                ('DistrictName', models.CharField(blank=True, max_length=1000, null=True)),
                ('POB', models.CharField(blank=True, max_length=1000, null=True)),
                ('PostCode', models.CharField(blank=True, max_length=1000, null=True)),
                ('City', models.CharField(max_length=1000)),
                ('CountrySubentity', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BirthInfoType_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BirthDate', models.DateField(blank=True, null=True)),
                ('City', models.CharField(blank=True, max_length=1000, null=True)),
                ('CitySubentity', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ControllingPerson_Type_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CtrlgPersonType', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CorrectableAccountReport_Type_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CorrectableOrganisationParty_Type_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CorrectablePoolReport_Type_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountCount', models.IntegerField()),
                ('AccountPoolReportType', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CountryInfoType_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CountryCode', models.CharField(max_length=1000)),
                ('FormerCountryName', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CRS_OECD_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrsBody_Type_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReportingFI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CrsBody_Type_ReportingFI_CorrectableOrganisationParty_Type', to='crs.CorrectableOrganisationParty_Type_model')),
            ],
        ),
        migrations.CreateModel(
            name='DocSpec_Type_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DocTypeIndic', models.CharField(max_length=1000)),
                ('DocRefId', models.CharField(max_length=1000)),
                ('CorrMessageRefId', models.CharField(blank=True, max_length=1000, null=True)),
                ('CorrDocRefId', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FIAccountNumber_Type_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AcctNumberType', models.CharField(blank=True, max_length=1000, null=True)),
                ('UndocumentedAccount', models.NullBooleanField()),
                ('ClosedAccount', models.NullBooleanField()),
                ('DormantAccount', models.NullBooleanField()),
                ('valueOf_x', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='FirstNameType_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xnlNameType', models.CharField(blank=True, max_length=1000, null=True)),
                ('valueOf_x', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='LastNameType_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xnlNameType', models.CharField(blank=True, max_length=1000, null=True)),
                ('valueOf_x', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='MessageSpec_Type_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SendingCompanyIN', models.CharField(blank=True, max_length=1000, null=True)),
                ('TransmittingCountry', models.CharField(max_length=1000)),
                ('ReceivingCountry', models.CharField(max_length=1000)),
                ('MessageType', models.CharField(max_length=1000)),
                ('Warning', models.CharField(blank=True, max_length=1000, null=True)),
                ('Contact', models.CharField(blank=True, max_length=1000, null=True)),
                ('MessageRefId', models.CharField(max_length=1000)),
                ('MessageTypeIndic', models.CharField(blank=True, max_length=1000, null=True)),
                ('CorrMessageRefId', models.CharField(blank=True, max_length=1000, null=True)),
                ('ReportingPeriod', models.DateField()),
                ('Timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MiddleNameType_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xnlNameType', models.CharField(blank=True, max_length=1000, null=True)),
                ('valueOf_x', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='MonAmnt_Type_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currCode', models.CharField(max_length=1000)),
                ('valueOf_x', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='NameOrganisation_Type_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameType', models.CharField(blank=True, max_length=1000, null=True)),
                ('valueOf_x', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='NamePerson_Type_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameType', models.CharField(blank=True, max_length=1000, null=True)),
                ('PrecedingTitle', models.CharField(blank=True, max_length=1000, null=True)),
                ('Title', models.CharField(blank=True, max_length=1000, null=True)),
                ('GenerationIdentifier', models.CharField(blank=True, max_length=1000, null=True)),
                ('Suffix', models.CharField(blank=True, max_length=1000, null=True)),
                ('GeneralSuffix', models.CharField(blank=True, max_length=1000, null=True)),
                ('FirstName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NamePerson_Type_FirstName_FirstNameType', to='crs.FirstNameType_model')),
                ('LastName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NamePerson_Type_LastName_LastNameType', to='crs.LastNameType_model')),
                ('MiddleName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NamePerson_Type_MiddleName_MiddleNameType', to='crs.MiddleNameType_model')),
            ],
        ),
        migrations.CreateModel(
            name='NamePrefixType_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xnlNameType', models.CharField(blank=True, max_length=1000, null=True)),
                ('valueOf_x', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationIN_Type_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuedBy', models.CharField(blank=True, max_length=1000, null=True)),
                ('INType', models.CharField(blank=True, max_length=1000, null=True)),
                ('valueOf_x', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationParty_Type_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ResCountryCode', models.CharField(blank=True, max_length=1000, null=True)),
                ('Address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrganisationParty_Type_Address_Address_Type', to='crs.Address_Type_model')),
                ('IN', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OrganisationParty_Type_IN_OrganisationIN_Type', to='crs.OrganisationIN_Type_model')),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrganisationParty_Type_Name_NameOrganisation_Type', to='crs.NameOrganisation_Type_model')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Type_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=1000)),
                ('PaymentAmnt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Payment_Type_PaymentAmnt_MonAmnt_Type', to='crs.MonAmnt_Type_model')),
            ],
        ),
        migrations.CreateModel(
            name='PersonParty_Type_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ResCountryCode', models.CharField(max_length=1000)),
                ('Nationality', models.CharField(blank=True, max_length=1000, null=True)),
                ('Address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PersonParty_Type_Address_Address_Type', to='crs.Address_Type_model')),
                ('BirthInfo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PersonParty_Type_BirthInfo_BirthInfoType', to='crs.BirthInfoType_model')),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PersonParty_Type_Name_NamePerson_Type', to='crs.NamePerson_Type_model')),
            ],
        ),
        migrations.CreateModel(
            name='ReportingGroupType_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountReport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ReportingGroupType_AccountReport_CorrectableAccountReport_Type', to='crs.CorrectableAccountReport_Type_model')),
                ('Intermediary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ReportingGroupType_Intermediary_CorrectableOrganisationParty_Type', to='crs.CorrectableOrganisationParty_Type_model')),
                ('PoolReport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ReportingGroupType_PoolReport_CorrectablePoolReport_Type', to='crs.CorrectablePoolReport_Type_model')),
                ('Sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ReportingGroupType_Sponsor_CorrectableOrganisationParty_Type', to='crs.CorrectableOrganisationParty_Type_model')),
            ],
        ),
        migrations.CreateModel(
            name='TIN_Type_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuedBy', models.CharField(blank=True, max_length=1000, null=True)),
                ('valueOf_x', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='crs',
        ),
        migrations.AddField(
            model_name='personparty_type_model',
            name='TIN',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PersonParty_Type_TIN_TIN_Type', to='crs.TIN_Type_model'),
        ),
        migrations.AddField(
            model_name='nameperson_type_model',
            name='NamePrefix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NamePerson_Type_NamePrefix_NamePrefixType', to='crs.NamePrefixType_model'),
        ),
        migrations.AddField(
            model_name='crsbody_type_model',
            name='ReportingGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CrsBody_Type_ReportingGroup_ReportingGroupType', to='crs.ReportingGroupType_model'),
        ),
        migrations.AddField(
            model_name='crs_oecd_model',
            name='CrsBody',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CRS_OECD_CrsBody_CrsBody_Type', to='crs.CrsBody_Type_model'),
        ),
        migrations.AddField(
            model_name='crs_oecd_model',
            name='MessageSpec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CRS_OECD_MessageSpec_MessageSpec_Type', to='crs.MessageSpec_Type_model'),
        ),
        migrations.AddField(
            model_name='correctablepoolreport_type_model',
            name='DocSpec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CorrectablePoolReport_Type_DocSpec_DocSpec_Type', to='crs.DocSpec_Type_model'),
        ),
        migrations.AddField(
            model_name='correctablepoolreport_type_model',
            name='PoolBalance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CorrectablePoolReport_Type_PoolBalance_MonAmnt_Type', to='crs.MonAmnt_Type_model'),
        ),
        migrations.AddField(
            model_name='correctableorganisationparty_type_model',
            name='DocSpec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CorrectableOrganisationParty_Type_DocSpec_DocSpec_Type', to='crs.DocSpec_Type_model'),
        ),
        migrations.AddField(
            model_name='correctableorganisationparty_type_model',
            name='OrganisationParty_Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crs.OrganisationParty_Type_model'),
        ),
        migrations.AddField(
            model_name='correctableaccountreport_type_model',
            name='AccountBalance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CorrectableAccountReport_Type_AccountBalance_MonAmnt_Type', to='crs.MonAmnt_Type_model'),
        ),
        migrations.AddField(
            model_name='correctableaccountreport_type_model',
            name='AccountHolder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CorrectableAccountReport_Type_AccountHolder_AccountHolder_Type', to='crs.AccountHolder_Type_model'),
        ),
        migrations.AddField(
            model_name='correctableaccountreport_type_model',
            name='AccountNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CorrectableAccountReport_Type_AccountNumber_FIAccountNumber_Type', to='crs.FIAccountNumber_Type_model'),
        ),
        migrations.AddField(
            model_name='correctableaccountreport_type_model',
            name='ControllingPerson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CorrectableAccountReport_Type_ControllingPerson_ControllingPerson_Type', to='crs.ControllingPerson_Type_model'),
        ),
        migrations.AddField(
            model_name='correctableaccountreport_type_model',
            name='DocSpec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CorrectableAccountReport_Type_DocSpec_DocSpec_Type', to='crs.DocSpec_Type_model'),
        ),
        migrations.AddField(
            model_name='correctableaccountreport_type_model',
            name='Payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CorrectableAccountReport_Type_Payment_Payment_Type', to='crs.Payment_Type_model'),
        ),
        migrations.AddField(
            model_name='controllingperson_type_model',
            name='Individual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ControllingPerson_Type_Individual_PersonParty_Type', to='crs.PersonParty_Type_model'),
        ),
        migrations.AddField(
            model_name='birthinfotype_model',
            name='CountryInfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BirthInfoType_CountryInfo_CountryInfoType', to='crs.CountryInfoType_model'),
        ),
        migrations.AddField(
            model_name='address_type_model',
            name='AddressFix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Address_Type_AddressFix_AddressFix_Type', to='crs.AddressFix_Type_model'),
        ),
        migrations.AddField(
            model_name='accountholder_type_model',
            name='Individual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AccountHolder_Type_Individual_PersonParty_Type', to='crs.PersonParty_Type_model'),
        ),
        migrations.AddField(
            model_name='accountholder_type_model',
            name='Organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AccountHolder_Type_Organisation_OrganisationParty_Type', to='crs.OrganisationParty_Type_model'),
        ),
    ]
